//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRequerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleRequerimiento()
        {
            this.ItemAtributo = new HashSet<ItemAtributo>();
        }
    
        public int Id { get; set; }
        public int IdRequerimiento { get; set; }
        public int IdTipoMaterial { get; set; }
        public int IdCategoriaValorizacion { get; set; }
        public string GrupoArticulo { get; set; }
        public string UnidadMedida { get; set; }
        public int IdSegmento { get; set; }
        public int IdGrupo { get; set; }
        public int IdClase { get; set; }
        public string Descripcion { get; set; }
        public int IdSegmentoOnu { get; set; }
        public int IdFamiliaOnu { get; set; }
        public int IdClaseOnu { get; set; }
    
        public virtual ClaseONU ClaseONU { get; set; }
        public virtual FamiliaONU FamiliaONU { get; set; }
        public virtual Requerimiento Requerimiento { get; set; }
        public virtual SegmentoONU SegmentoONU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemAtributo> ItemAtributo { get; set; }
    }
}
