//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRO
    {
        public int CODIGO_PARAMETRO { get; set; }
        public System.Guid CODIGO_EMPRESA { get; set; }
        public Nullable<System.Guid> CODIGO_SISTEMA { get; set; }
        public string CODIGO_IDENTIFICADOR { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public bool INDICADOR_EMPRESA { get; set; }
        public bool INDICADOR_PERMITE_AGREGAR { get; set; }
        public bool INDICADOR_PERMITE_MODIFICAR { get; set; }
        public bool INDICADOR_PERMITE_ELIMINAR { get; set; }
        public string TIPO_PARAMETRO { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string TERMINAL_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string TERMINAL_MODIFICACION { get; set; }
    }
}
