//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRO_SECCION
    {
        public int CODIGO_PARAMETRO { get; set; }
        public int CODIGO_SECCION { get; set; }
        public string NOMBRE { get; set; }
        public string CODIGO_TIPO_DATO { get; set; }
        public bool INDICADOR_PERMITE_MODIFICAR { get; set; }
        public bool INDICADOR_OBLIGATORIO { get; set; }
        public bool INDICADOR_SISTEMA { get; set; }
        public Nullable<int> CODIGO_PARAMETRO_RELACIONADO { get; set; }
        public Nullable<int> CODIGO_SECCION_RELACIONADO { get; set; }
        public Nullable<int> CODIGO_SECCION_RELACIONADO_MOSTRAR { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string TERMINAL_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string TERMINAL_MODIFICACION { get; set; }
    }
}
