//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using Pe.Stracon.Models.DTO;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STRACON_SGCOEntities : DbContext
    {
        public STRACON_SGCOEntities()
            : base("name=STRACON_SGCOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atributo> Atributo { get; set; }
        public virtual DbSet<CategoriaValorizacion> CategoriaValorizacion { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Requerimiento> Requerimiento { get; set; }
        public virtual DbSet<Segmento> Segmento { get; set; }
        public virtual DbSet<TipoMaterial> TipoMaterial { get; set; }
        public virtual DbSet<TabClaMaterial> TabClaMaterial { get; set; }
        public virtual DbSet<PARAMETRO> PARAMETRO { get; set; }
        public virtual DbSet<PARAMETRO_SECCION> PARAMETRO_SECCION { get; set; }
        public virtual DbSet<PARAMETRO_VALOR> PARAMETRO_VALOR { get; set; }
        public virtual DbSet<ItemAtributo> ItemAtributo { get; set; }
        public virtual DbSet<Adjunto> Adjunto { get; set; }
        public virtual DbSet<RolesAceptados> RolesAceptados { get; set; }
        public virtual DbSet<ClaseONU> ClaseONU { get; set; }
        public virtual DbSet<FamiliaONU> FamiliaONU { get; set; }
        public virtual DbSet<SegmentoONU> SegmentoONU { get; set; }
        public virtual DbSet<DetalleRequerimiento> DetalleRequerimiento { get; set; }
    }
}
