//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STRACON_POLITICASEntities : DbContext
    {
        public STRACON_POLITICASEntities()
            : base("name=STRACON_POLITICASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TRABAJADOR> TRABAJADOR { get; set; }
        public virtual DbSet<PARAMETRO_SECCION> PARAMETRO_SECCION { get; set; }
        public virtual DbSet<PARAMETRO_VALOR> PARAMETRO_VALOR { get; set; }
    }
}
