//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.User_Profile = new HashSet<User_Profile>();
            this.Profile_Role = new HashSet<Profile_Role>();
        }
    
        public int N_ID_PROFILE { get; set; }
        public string S_NAME { get; set; }
        public string S_DESCRIPTION { get; set; }
        public string S_STATUS_REGISTER { get; set; }
        public string S_USER_CREATION { get; set; }
        public Nullable<System.DateTime> D_DATE_CREATION { get; set; }
        public string S_TERMINAL_CREATION { get; set; }
        public string S_USER_MODIFICATION { get; set; }
        public Nullable<System.DateTime> D_DATE_MODIFICATION { get; set; }
        public string S_TERMINAL_MODIFICATION { get; set; }
        public string S_OBSERVATION { get; set; }
        public Nullable<System.DateTime> D_DATE_TERMINATE_REGISTER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Profile> User_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_Role> Profile_Role { get; set; }
    }
}
