//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requerimiento()
        {
            this.Adjunto = new HashSet<Adjunto>();
            this.DetalleRequerimiento = new HashSet<DetalleRequerimiento>();
        }
    
        public int Id { get; set; }
        public string CentroLogistico { get; set; }
        public string Solicitante { get; set; }
        public string Estado { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string AprobadoPor { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string AceptadoPor { get; set; }
        public Nullable<System.DateTime> FechaAceptacion { get; set; }
        public string TerminadoPor { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public string RechazadoPor { get; set; }
        public Nullable<System.DateTime> FechaRechazo { get; set; }
        public string RazonRechazo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjunto> Adjunto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRequerimiento> DetalleRequerimiento { get; set; }
    }
}
