//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSRAGyMEntities : DbContext
    {
        public dbSRAGyMEntities()
            : base("name=dbSRAGyMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Profile_Role> Profile_Role { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Role_System> Role_System { get; set; }
        public virtual DbSet<SystemSRA> SystemSRA { get; set; }
        public virtual DbSet<User_Profile> User_Profile { get; set; }
        public virtual DbSet<UserSRA> UserSRA { get; set; }
    }
}
