//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabClaMaterial
    {
        public string cCodSegmento { get; set; }
        public string vNomSegmento { get; set; }
        public string cCodGrupo { get; set; }
        public string vNomGrupo { get; set; }
        public string cCodClase { get; set; }
        public string vNomClase { get; set; }
        public string cCodAtributo { get; set; }
        public string vNomAtributo { get; set; }
        public Nullable<byte> tiOrden { get; set; }
        public Nullable<bool> bObligatorio { get; set; }
        public string vCodUsuCreacion { get; set; }
        public System.DateTime sdFecCreacion { get; set; }
        public string vNomTerCreacion { get; set; }
        public string vCodUsuModificacion { get; set; }
        public Nullable<System.DateTime> sdFecActModificacion { get; set; }
        public string vNomTerModificacion { get; set; }
    }
}
