//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Stracon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        public int N_ID_USER_PROFILE { get; set; }
        public int N_ID_USER { get; set; }
        public int N_ID_PROFILE { get; set; }
        public string S_STATUS_REGISTER { get; set; }
        public Nullable<System.DateTime> D_DATE_START_VALIDITY { get; set; }
        public string S_USER_CREATION { get; set; }
        public Nullable<System.DateTime> D_DATE_CREATION { get; set; }
        public string S_TERMINAL_CREATION { get; set; }
        public string S_USER_MODIFICATION { get; set; }
        public Nullable<System.DateTime> D_DATE_MODIFICATION { get; set; }
        public string S_TERMINAL_MODIFICATION { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual UserSRA UserSRA { get; set; }
    }
}
